### ---PROFESSORS

GET http://localhost:8080/api/professors

###

GET http://localhost:8080/api/professors
page: 0

###

GET http://localhost:8080/api/professors
page: 0
pageSize: 2

###

GET http://localhost:8080/api/professors?term=Рис

###

GET http://localhost:8080/api/professors/kostadin.mishev

###



### ---ROOMS

GET http://localhost:8080/api/rooms

###

GET http://localhost:8080/api/rooms/ordered

###

GET http://localhost:8080/api/rooms?term=11

###

GET http://localhost:8080/api/rooms/1

###

POST http://localhost:8080/api/rooms
Content-Type: application/x-www-form-urlencoded

name=007&buildingId=1&description=Спроти%20студентски%20прашања

###

PATCH http://localhost:8080/api/rooms/20
Content-Type: application/x-www-form-urlencoded

name=008&buildingId=2&description=На%20трети%20кат

###

DELETE http://localhost:8080/api/rooms/20

###


### ---BUILDINGS

GET http://localhost:8080/api/buildings

###

GET http://localhost:8080/api/buildings/ordered

###

GET http://localhost:8080/api/buildings/1

###

POST http://localhost:8080/api/buildings
Content-Type: application/x-www-form-urlencoded

name=DEK&description=Спроти%20ТМФ

###

PATCH http://localhost:8080/api/buildings/5
Content-Type: application/x-www-form-urlencoded

name=DEKANAT&description=Деканат%20-%20Зградата%20спроти%20ТМФ

###

DELETE http://localhost:8080/api/buildings/5

###


### ---STUDENTS

GET http://localhost:8080/api/students/170001

###

POST http://localhost:8080/api/students/add
Content-Type: application/x-www-form-urlencoded

slotId=1&index=170006

###

POST http://localhost:8080/api/students/remove
Content-Type: application/x-www-form-urlencoded

slotId=1&index=170006

###

GET http://localhost:8080/api/students/bySlotId/1

###

GET http://localhost:8080/api/students/bySlotId/1
page: 0

###

GET http://localhost:8080/api/students/bySlotId/1
page: 0
pageSize:2

###

POST http://localhost:8080/api/students/follow
Content-Type: application/x-www-form-urlencoded

index=170005&professorId=dimitar.trajanov

###

POST http://localhost:8080/api/students/unfollow
Content-Type: application/x-www-form-urlencoded

index=170005&professorId=dimitar.trajanov

###


### ---CONSULTATIONS

GET http://localhost:8080/api/consultations/1

###

POST http://localhost:8080/api/consultations
Content-Type: application/x-www-form-urlencoded

professorId=kostadin.mishev&roomId=14&date=04/02/2020&from=12:00&to=13:30

###

POST http://localhost:8080/api/consultations
Content-Type: application/x-www-form-urlencoded

professorId=kostadin.mishev&roomId=14&dayOfWeek=WEDNESDAY&from=12:00&to=13:30

###

PATCH http://localhost:8080/api/consultations/7
Content-Type: application/x-www-form-urlencoded

professorId=kostadin.mishev&roomId=14&date=03/02/2020&from=12:30&to=13:45

###

DELETE http://localhost:8080/api/consultations/7

###