### ---PROFESSORS

GET http://localhost:8080/api/professors

###

GET http://localhost:8080/api/professors
page: 0

###

GET http://localhost:8080/api/professors
page: 0
pageSize: 2

###

GET http://localhost:8080/api/professors?term=Рис

###



### ---ROOMS

GET http://localhost:8080/api/rooms

###

GET http://localhost:8080/api/rooms/ordered

###

GET http://localhost:8080/api/rooms?term=11

###

GET http://localhost:8080/api/rooms/1

###

POST http://localhost:8080/api/rooms
Content-Type: application/x-www-form-urlencoded

name=007&buildingId=1&description=Спроти%20студентски%20прашања

###

PATCH http://localhost:8080/api/rooms/20
Content-Type: application/x-www-form-urlencoded

name=008&buildingId=2&description=На%20трети%20кат

###

DELETE http://localhost:8080/api/rooms/20

###


### ---BUILDINGS

GET http://localhost:8080/api/buildings

###

GET http://localhost:8080/api/buildings/ordered

###

GET http://localhost:8080/api/buildings/1

###

POST http://localhost:8080/api/buildings
Content-Type: application/x-www-form-urlencoded

name=DEK&description=Спроти%20ТМФ

###

PATCH http://localhost:8080/api/buildings/5
Content-Type: application/x-www-form-urlencoded

name=DEKANAT&description=Деканат%20-%20Зградата%20спроти%20ТМФ

###

DELETE http://localhost:8080/api/buildings/5

###
